# Generated by Django 3.0.7 on 2020-12-20 13:22

from django.db import migrations, models
import fix_the_news.users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=254, validators=[fix_the_news.users.validators.EmailValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
