# Generated by Django 3.0.4 on 2020-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='communication',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type',
            field=models.CharField(choices=[('about', 'about'), ('daily', 'daily'), ('privacy', 'privacy'), ('registration', 'registration'), ('terms_and_conditions', 'terms_and_conditions'), ('welcome', 'welcome')], max_length=50),
        ),
    ]
