# Generated by Django 3.0.4 on 2020-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'User with that username already exists.'}, max_length=254, unique=True, verbose_name='username'),
        ),
    ]
