# Generated by Django 3.0.4 on 2020-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_username_removed_first_and_last_names_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
