# Generated by Django 3.0.4 on 2020-08-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_thumbnail_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_viewed_daily_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_viewed_welcome_communication',
            field=models.BooleanField(default=False),
        ),
    ]
