# Generated by Django 3.0.4 on 2020-08-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_added_communication_fields_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_viewed_welcome_communication',
            new_name='has_viewed_registration_communication',
        ),
    ]
