# Generated by Django 3.0.4 on 2020-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_field_to_has_viewed_registration_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_to_emails',
            field=models.BooleanField(default=True),
        ),
    ]
