# Generated by Django 3.0.4 on 2020-09-03 21:51

from django.db import migrations, models
import fix_the_news.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_email_field_for_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=254, validators=[fix_the_news.users.validators.EmailValidator()]),
        ),
    ]
