# Generated by Django 3.0.7 on 2020-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_validate_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_upload_limit',
            field=models.BooleanField(default=False, help_text='If true this user ignores upload limits for topics and articles'),
        ),
    ]
