# Generated by Django 3.0.7 on 2020-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscribe_to_emails_default_is_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=254, verbose_name='name'),
            preserve_default=False,
        ),
    ]
