# Generated by Django 3.0.7 on 2020-10-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_fill_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
