version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate --settings=settings.circle_ci
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test fix_the_news --settings=settings.circle_ci
      - store_artifacts:
          path: test-reports/
          destination: python_app
