# Generated by Django 3.0.4 on 2020-04-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0003_news_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='type',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
    ]
