# Generated by Django 3.0.4 on 2020-08-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0005_news_item_views_and_score_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='views',
        ),
    ]
