# Generated by Django 3.0.4 on 2020-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0006_remove_newsitem_views'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['score'], name='news_items__score_aa117c_idx'),
        ),
    ]
