# Generated by Django 3.0.4 on 2020-08-10 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0007_index_score_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='score_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
