# Generated by Django 3.0.7 on 2020-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0008_newsitem_score_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.TextField(),
        ),
    ]
