# Generated by Django 3.0.7 on 2020-09-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0009_url_now_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='score_data',
        ),
    ]
