# Generated by Django 3.0.7 on 2020-11-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0010_remove_newsitem_score_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_item_images'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='original_image_url',
            field=models.TextField(default=''),
        ),
    ]
