# Generated by Django 3.0.7 on 2020-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0011_news_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='tried_to_add_image',
            field=models.BooleanField(default=False),
        ),
    ]
