# Generated by Django 4.1.7 on 2023-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0013_alter_newsitem_id_alter_newssource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='description_from_source',
            field=models.TextField(blank=True, default='', help_text="Description from the url source page taken content found in meta tag: <meta name='description' content='blah blah blah' />"),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_from_source',
            field=models.CharField(blank=True, default='', help_text='Title from the url source page taken from first H1 tag', max_length=254),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
