# Generated by Django 3.0.4 on 2020-06-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_fill_existing_slug_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
