# Generated by Django 3.0.4 on 2020-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_slug_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
