# Generated by Django 3.0.7 on 2020-09-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_priority_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
