# Generated by Django 3.0.4 on 2020-08-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_items', '0006_remove_newsitem_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=254)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='news_items.NewsItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
